default: &default
  host: localhost
  username: postgres
  adapter: postgresql
  pool: 10

development:
  <<: *default
  database: homebase_development
  pool: 4

production: &production 
  <<: *default
  database: homebase_development

test: &test 
  <<: *default
  database: homebase_test

assets:
  <<: *test

